server:
  port: 8181
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/nw
   username: root
   password: root
   
mybatis:
  mapper-locations: classpath:/mapper/*.xml  configuration-properties:   #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
   map-underscore-to-camel-case: true
  

logging:
  level:
     com.could.provider.user.mappers : debug

spring.devtools.restart.enabled: true