security:  basic:    enabled: true  user:      name: root     password: root
server:
  port: 8761
  
eureka:  client:    fetch-registry: false    register-with-eureka: false
    service-url:      defaultZone: http://root:root@localhost:8761/eureka/
    
